extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
env:
  node: true
  jest: true
ignorePatterns:
  - '**/dist'
  - '**/node_modules'
  - '**/*.js'
plugins:
  - '@typescript-eslint'
  - prettier
parser: '@typescript-eslint/parser'
rules:
  no-unused-vars: off
  no-console: off
  'prettier/prettier': error
  '@typescript-eslint/explicit-function-return-type': error
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
