arrowParens: always
bracketSameLine: true
bracketSpacing: true
endOfLine: lf
printWidth: 120
semi: false
singleQuote: true
trailingComma: all
useTabs: false

overrides:
  - files: '*.md'
    options:
      tabWidth: 1
  - files: '*.{json,eslintrc,prettierrc}'
    options:
      tabWidth: 2
      useTabs: false

plugins:
  - "@trivago/prettier-plugin-sort-imports"

importOrder:
  - <THIRD_PARTY_MODULES>
  - ^@tweekr/(.*)$
  - ^[./]
importOrderParserPlugins:
  - typescript
  - jsx
  - decorators-legacy
importOrderSeparation: true
importOrderSortSpecifiers: true
