components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas: {}
    securitySchemes:
        bearer_auth:
            type: http
            scheme: bearer
info:
    title: '@tweekr/{name}'
    version: 0.1.0
    contact:
        name: tweekr.io
openapi: 3.0.0
paths:
    /health:
        get:
            operationId: GetHealthCheck
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                properties:
                                    ok: {type: boolean, enum: [true], nullable: false}
                                required:
                                    - ok
                                type: object
            summary: CreateOne
            security: []
            parameters: []
servers:
    -
        url: /
